### ISSUE TITLE
[BUG] Some LaTeX, some is not

### ISSUE THREAD

**Issue by ghost** [aledeg/xExtension-LatexSupport#2]
Hi,

I just noticed that some LaTeX on my feeds is rendered and some isn't. You can see it in this [feed](http://export.arxiv.org/rss/cond-mat) for instance. Here is a picture of where you can find this: 
![image](https://user-images.githubusercontent.com/1509146/120445519-f9de5c00-c388-11eb-83d9-3b46f32b2076.png)

Moreover, the console is showing some errors which I think might be related: see [here](https://pastebin.com/y5rSpwaj).

Thank you for your help!

**Comment by aledeg** [comment]
What browser are you using? It might be related to an error in the font loading.
What is the URL of the feed?

**Comment by ghost** [comment]
Hi,
I reinstalled the extension and it seems the problem disappeared, so not fully sure what happened but I will close for now.
Thank you!
